version: '2'

networks:
    database:
        driver: bridge
services:
    db:
        image: postgres:14.13
        environment:
            POSTGRES_PASSWORD: app_pass
            POSTGRES_USER: app_user
            POSTGRES_DB: app_db
            CLUSTER_NODE_NETWORK_NAME: appdb
            NODE_ID: 1
            NODE_NAME: node1
        ports:
            - "5432:5432"
        networks:
            database:
                aliases:
                    - database

    myadmin:
        image: dpage/pgadmin4:8.11
        environment:
            PGADMIN_DEFAULT_EMAIL: test@test.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - "82:80"
        depends_on:
            - db
        networks:
            database:
                aliases:
                    - database
